name: piano_analytics_plugin
description: A flutter plugin for use piano anlaytics SDK. Piano Analytics is the logical progression to our Analytics Suite 2
version: 0.0.7
homepage: https://github.com/alex596/piano_analytics_plugin

environment:
  sdk: ^3.5.2
  flutter: ^3.24.2

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.piano_analytics_plugin
        pluginClass: PianoAnalyticsPlugin
      ios:
        pluginClass: PianoAnalyticsPlugin
